# Generated by Django 6.0 on 2025-12-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HOSP', 'Hospital'), ('FARM', 'Farmácia'), ('POST', 'Posto de Saúde')], max_length=4)),
                ('descricao', models.TextField(blank=True, help_text='Ex: Horários, especialidades')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
