# Generated by Django 6.0 on 2025-12-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosaude',
            name='horario',
            field=models.CharField(blank=True, help_text='Ex: Seg a Sex, 08:00 - 18:00', max_length=100, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AddField(
            model_name='pontosaude',
            name='medicamentos',
            field=models.TextField(blank=True, help_text='Ex: Dipirona, Insulina, Losartana', verbose_name='Medicamentos Disponíveis'),
        ),
        migrations.AddField(
            model_name='pontosaude',
            name='servicos',
            field=models.TextField(blank=True, help_text='Separe por vírgulas. Ex: Vacinação, Curativos, Dentista', verbose_name='Serviços Prestados'),
        ),
        migrations.AlterField(
            model_name='pontosaude',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Observações Gerais'),
        ),
    ]
