# Generated by Django 6.0 on 2025-12-15 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pontosaude_horario_pontosaude_medicamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosaude',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='pontosaude',
            name='horario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pontosaude',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='pontosaude',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='pontosaude',
            name='medicamentos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pontosaude',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pontosaude',
            name='servicos',
            field=models.TextField(blank=True),
        ),
    ]
