# Generated by Django 6.0 on 2026-03-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pontosaude_descricao_alter_pontosaude_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_medicamentos', to='core.pontosaude')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_medicos', to='core.pontosaude')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoGratuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_produtos', to='core.pontosaude')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_vacinas', to='core.pontosaude')),
            ],
        ),
    ]
