# Generated by Django 6.0 on 2026-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicamento_medico_produtogratuito_vacina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosaude',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fachadas/'),
        ),
    ]
