# Generated by Django 6.0 on 2026-03-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pontosaude_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosaude',
            name='medicamentos',
        ),
        migrations.AddField(
            model_name='pontosaude',
            name='medicamentos_texto',
            field=models.TextField(blank=True, help_text='Descrição textual de medicamentos', verbose_name='Medicamentos (Texto)'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pontosaude',
            name='servicos',
            field=models.TextField(blank=True, help_text='Liste os serviços prestados'),
        ),
    ]
